# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: monitor.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'monitor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmonitor.proto\x12\x07monitor\"\x07\n\x05\x45mpty\" \n\x0c\x42oolResponse\x12\x10\n\x08is_ready\x18\x01 \x01(\x08\"+\n\x08UdpStats\x12\x0f\n\x07packets\x18\x01 \x01(\x04\x12\x0e\n\x06\x61\x42ytes\x18\x02 \x01(\x04\x32y\n\x0eMonitorService\x12\x30\n\x07IsReady\x12\x0e.monitor.Empty\x1a\x15.monitor.BoolResponse\x12\x35\n\x10GetUdpStatistics\x12\x0e.monitor.Empty\x1a\x11.monitor.UdpStatsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_BOOLRESPONSE']._serialized_start=35
  _globals['_BOOLRESPONSE']._serialized_end=67
  _globals['_UDPSTATS']._serialized_start=69
  _globals['_UDPSTATS']._serialized_end=112
  _globals['_MONITORSERVICE']._serialized_start=114
  _globals['_MONITORSERVICE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
